# Generated by Django 4.1.7 on 2023-03-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
